using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraMovement : MonoBehaviour
{
    [Header("Movement Attributes")]
    [SerializeField] private float panSpeed = 30f;
    [SerializeField] private float scrollSpeed;
    [SerializeField] private float minY;
    [SerializeField] private float maxY;
    private bool doMove = true;

    void Update()
    {
        Movement();
    }

    void Movement()
	{

        if (Input.GetKey("w") )
		{
            transform.Translate(Vector3.forward * panSpeed * Time.deltaTime, Space.World);
		}
        if (Input.GetKey("s"))
        {
            transform.Translate(Vector3.back * panSpeed * Time.deltaTime, Space.World);
        }
        if (Input.GetKey("a"))
        {
            transform.Translate(Vector3.left * panSpeed * Time.deltaTime, Space.World);
        }
        if (Input.GetKey("d"))
        {
            transform.Translate(Vector3.right * panSpeed * Time.deltaTime, Space.World);
        }

        float scroll = Input.GetAxis("Mouse ScrollWheel");

        Vector3 pos = transform.position;

        pos.y -= scroll * 1000 * scrollSpeed * Time.deltaTime;
        pos.y = Mathf.Clamp(pos.y, minY, maxY);

        transform.position = pos;
    }

}
